export const COMMENT_TYPES = {
  CREATE_COMMENT: 'CREATE_COMMENT',
  GET_COMMENTS: 'GET_COMMENTS',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  REPLY_COMMENT: 'REPLY_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_REPLY: 'DELETE_REPLY'
};